// File: lib/firebase_options.dart
// Auto-generated by FlutterFire CLI.
// Do not modify manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Throw an error or return specific options if you configure Windows
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        // Throw an error or return specific options if you configure Linux
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- Placeholder Web Options ---
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBU_Q2F0zIMTrIyh5nXERtU3fEtlSX4SH0",
      authDomain: "mystical-slate-448113-c6.firebaseapp.com",
      projectId: "mystical-slate-448113-c6",
      storageBucket: "mystical-slate-448113-c6.firebasestorage.app",
      messagingSenderId: "681914071632",
      appId: "1:681914071632:web:35d31b8d1dafb51d51ef55",
      measurementId: "G-HQSH8R6RF9");

  // --- Placeholder Android Options ---
  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBU_Q2F0zIMTrIyh5nXERtU3fEtlSX4SH0",
      authDomain: "mystical-slate-448113-c6.firebaseapp.com",
      projectId: "mystical-slate-448113-c6",
      storageBucket: "mystical-slate-448113-c6.firebasestorage.app",
      messagingSenderId: "681914071632",
      appId: "1:681914071632:web:35d31b8d1dafb51d51ef55",
      measurementId: "G-HQSH8R6RF9");

  // --- Placeholder iOS Options ---
  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyBU_Q2F0zIMTrIyh5nXERtU3fEtlSX4SH0",
      authDomain: "mystical-slate-448113-c6.firebaseapp.com",
      projectId: "mystical-slate-448113-c6",
      storageBucket: "mystical-slate-448113-c6.firebasestorage.app",
      messagingSenderId: "681914071632",
      appId: "1:681914071632:web:35d31b8d1dafb51d51ef55",
      measurementId: "G-HQSH8R6RF9");

  // --- Placeholder macOS Options ---
  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyBU_Q2F0zIMTrIyh5nXERtU3fEtlSX4SH0",
      authDomain: "mystical-slate-448113-c6.firebaseapp.com",
      projectId: "mystical-slate-448113-c6",
      storageBucket: "mystical-slate-448113-c6.firebasestorage.app",
      messagingSenderId: "681914071632",
      appId: "1:681914071632:web:35d31b8d1dafb51d51ef55",
      measurementId: "G-HQSH8R6RF9");
}
